server:
  port: 8050

spring:
  application:
    name: zuul-edge-server
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://192.168.1.5:8081/customer
          predicates:
            - Path= /customer/**
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/